### ISSUE TITLE
ArrowSquid TODO

### ISSUE THREAD

**Issue by eldargab** [subsquid/squid-sdk#171]
- [x] integrate evm stage 2 archive
- [x] hot blocks for substrate
- [x] simplify block item type derivation in substrate processor
- [x] https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters
- [x] #138

**Comment by belopash** [comment]
- [ ] rename `@subsquid/util-internal-http-client` -> `@subsquid/http-client`

**Comment by belopash** [comment]
Hey @eldargab, has this been merged? As I remember, it hasn't
https://github.com/subsquid/squid-sdk/commit/606d6e42b7eb82bbfa9d034021a21bda0729612b
